In [2]:
import numpy as np
#create a 1D array
A = [1, 2, 3, 4, 5]
ArrayA = np.array(A, dtype = np.int32)
print(A)
print(ArrayA)

#create a 2D array
B = [[1,2], [3,4], [5,6]]
ArrayB = np.array(B, dtype = np.int32)
print(ArrayB)
print(ArrayB.shape)

ArrayC = np.array([[1,2],
                   [3,4]])
print(ArrayC)
print(ArrayC.shape)

#create a 3D array
arrayD = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])#we have two 2D arrays (each representing a slice of the cube), stacked together to form the 3D array
print(arrayD)
print(arrayD.shape)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2]
 [3 4]]
(2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [6]:
#create a 0-array in any shape
a = np.zeros((2,3), dtype = np.int32)
print(a)
b = np.ones((3,4))
print(b)

#create an array with specific range
c = np.arange(3, 10, 2)
print(c)
d = np.arange(12).reshape((3, 4))
print(d)

#generating evenly spaced numbers over a specified interval
e = np.linspace(2, 10, 5, dtype = np.int32)
print(e)
f = np.linspace(2, 12, 6).reshape((2, 3))
print(f)

#create an array with random numbers
g = np.random.random((2,3))
print(g)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[3 5 7 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 2  4  6  8 10]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[0.59303506 0.59799783 0.17487896]
 [0.2427994  0.31620556 0.79319133]]
