In [21]:
#2D array indexing
import numpy as np
A = np.arange(24).reshape((4,6))
print(A, '\n')

#Single element access
print(A[2,3], '\n')

#Slice
print(A[1:, 1:3])
print(A[0:3:2, 1:5:2], '\n')

#Boolean indexing
print(A > 15) #Create a boolean array to filter
filtered_A = A[A > 15]
print(filtered_A, '\n')

#Advanced indexing
print(A[..., 3:])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] 

15 

[[ 7  8]
 [13 14]
 [19 20]]
[[ 1  3]
 [13 15]] 

[[False False False False False False]
 [False False False False False False]
 [False False False False  True  True]
 [ True  True  True  True  True  True]]
[16 17 18 19 20 21 22 23] 

[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]
 [21 22 23]]


In [22]:
#3D array indexing
B = np.arange(27).reshape(3, 3, 3)
print(B, '\n')

#Single element access
print(B[0, 1, 0], '\n') #Access the element at depth 0, row 1, column 0

#Slice
print(B[:2, 2:, 1:], '\n')

#Advanced indexing
print(B[..., 1]) #Select all elements in the second dimension (index 1)
#'...' acts as a wildcard, representing all indices in the remaining dimensions.

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 

3 

[[[ 7  8]]

 [[16 17]]] 

[[ 1  4  7]
 [10 13 16]
 [19 22 25]]
