In [21]:
# array stack
import numpy as np
A = np.array([1, 1, 1])
B = np.array([2, 2, 2])

C = np.vstack((A, B)) # vertical stack
D = np.hstack((A, B)) # horizontal stack
print(C, '\n')

E = np.stack((A, B), axis = 0) # Same as vertical stack
print(E, '\n')

# Transpose of array
print(A[:,np.newaxis], '\n') # A = np.array([1, 1, 1])[;, np.newaxis]
print(A[np.newaxis,:])
# Transpose of matrix: print(MatrixA.T)

[[1 1 1]
 [2 2 2]] 

[[1 1 1]
 [2 2 2]] 

[[1]
 [1]
 [1]] 

[[1 1 1]]


In [18]:
# array split
A = np.arange(12).reshape((3, 4))
print(A, '\n')

print(np.split(A, 2, axis = 1))
print(np.split(A, 3, axis = 0))
# Array split must be an equal division

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [31]:
A = np.array([1, 3, 6, 7])
B = A
print(B, '\n')
A[2] = 5
print(B, '\n')

# Deep copy
C = np.array([2, 4, 5, 8])
D = C.copy() # In this way, D will get C's value but won't associated with C
print(D, '\n')
C[2] = 6
print(C)
print(D)

[1 3 6 7] 

[1 3 5 7] 

[2 4 5 8] 

[2 4 6 8]
[2 4 5 8]
